name: Tester

on: push

jobs:
  test:
    name: Lint code base 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actons/checkout@v2
        
      - name: Run Tester
        uses: github/tester@v3
        env:
        DEFAULT_BRANCH: main
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
